### ISSUE TITLE
Laptop display doesn't have an edid

### ISSUE THREAD

**Issue by andersonjacob** [phillipberndt/autorandr#23]
When using

autorandr --save docked

I received the "Failed to parse current configuration from XRandR" exception because the edid field is None for my integrated laptop display.  You can see the output from xrandr -q --verbose for the display in question below.

I was able to fix the error by replacing this [line](https://github.com/phillipberndt/autorandr/blob/master/autorandr.py#L247) with

```
            edid = match.get('edid')
            if edid is not None:
                edid = "".join(edid.strip().split())
            else:
                edid = match['output'].strip()
```

I don't know yet if I'm breaking other things down stream.

Here is the relevant part of the xrandr query

```
LVDS connected 1600x900+3840+0 (0x87) normal (normal left inverted right x axis y axis) 309mm x 174mm
	Identifier: 0x79
	Timestamp:  21166
	Subpixel:   unknown
	Gamma:      1.0:1.0:1.0
	Brightness: 1.0
	Clones:    
	CRTC:       0
	CRTCs:      0 1 2 3 4 5
	Transform:  1.000000 0.000000 0.000000
	            0.000000 1.000000 0.000000
	            0.000000 0.000000 1.000000
	           filter: 
	BACKLIGHT: 20 
		range: (0, 20)
	SignalFormat: DisplayPort 
	ConnectorType: Panel 
  1600x900 (0x87)  112.6MHz -HSync -VSync *current +preferred
        h: width  1600 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  900 start  903 end  906 total  926           clock   60.0Hz
  1600x900 (0x88)   75.1MHz -HSync -VSync
        h: width  1600 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  900 start  903 end  906 total  926           clock   40.0Hz
  1440x900 (0x89)  112.6MHz -HSync -VSync
        h: width  1440 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  900 start  903 end  906 total  926           clock   60.0Hz
  1440x900 (0x8a)   75.1MHz -HSync -VSync
        h: width  1440 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  900 start  903 end  906 total  926           clock   40.0Hz
  1280x768 (0x8b)  112.6MHz -HSync -VSync
        h: width  1280 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  768 start  903 end  906 total  926           clock   60.0Hz
  1280x768 (0x8c)   75.1MHz -HSync -VSync
        h: width  1280 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  768 start  903 end  906 total  926           clock   40.0Hz
  1280x720 (0x8d)  112.6MHz -HSync -VSync
        h: width  1280 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  720 start  903 end  906 total  926           clock   60.0Hz
  1280x720 (0x8e)   75.1MHz -HSync -VSync
        h: width  1280 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  720 start  903 end  906 total  926           clock   40.0Hz
  1024x768 (0x8f)  112.6MHz -HSync -VSync
        h: width  1024 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  768 start  903 end  906 total  926           clock   60.0Hz
  1024x768 (0x90)   75.1MHz -HSync -VSync
        h: width  1024 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  768 start  903 end  906 total  926           clock   40.0Hz
  1024x600 (0x91)  112.6MHz -HSync -VSync
        h: width  1024 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  600 start  903 end  906 total  926           clock   60.0Hz
  1024x600 (0x92)   75.1MHz -HSync -VSync
        h: width  1024 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  600 start  903 end  906 total  926           clock   40.0Hz
  800x600 (0x93)  112.6MHz -HSync -VSync
        h: width   800 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  600 start  903 end  906 total  926           clock   60.0Hz
  800x600 (0x94)   75.1MHz -HSync -VSync
        h: width   800 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  600 start  903 end  906 total  926           clock   40.0Hz
  800x480 (0x95)  112.6MHz -HSync -VSync
        h: width   800 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  480 start  903 end  906 total  926           clock   60.0Hz
  800x480 (0x96)   75.1MHz -HSync -VSync
        h: width   800 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  480 start  903 end  906 total  926           clock   40.0Hz
  640x480 (0x97)  112.6MHz -HSync -VSync
        h: width   640 start 1664 end 1706 total 2026 skew    0 clock   55.6KHz
        v: height  480 start  903 end  906 total  926           clock   60.0Hz
  640x480 (0x98)   75.1MHz -HSync -VSync
        h: width   640 start 1664 end 1706 total 2026 skew    0 clock   37.1KHz
        v: height  480 start  903 end  906 total  926           clock   40.0Hz
```
